<?php

namespace TvDatabase\HomeBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ShowController__JMSInjector
{
    public static function inject($container) {
        $instance = new \TvDatabase\HomeBundle\Controller\ShowController();
        return $instance;
    }
}
