#tv_database_login:
#    resource: "@TvDatabaseLoginBundle/Controller/"
#    type:     annotation
#    prefix:   /

tv_database_home:
    resource: "@TvDatabaseHomeBundle/Resources/config/routing.yml"
    prefix:   /

acme_store:
    resource: "@AcmeStoreBundle/Controller/"
    type:     annotation
    prefix:   /

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
    
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

#login:
#    pattern: /login
#    defaults: { _controller: TvDatabaseLoginBundle:Security:login }
#moja autentifikacija
#login_check: 
#    pattern: /login_check
    
#register:
#    pattern: /register
#    defaults: { _controller: TvDatabaseLoginBundle:Security:register }
    
#register_check:
#    pattern: /register_check
#    defaults: { _controller: TvDatabaseLoginBundle:Security:createUser }
#kraj moje autentifikacije

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile
    
_security_check: 
    pattern: /login_check
    defaults: { _controller: TvDatabaseHomeBundle:Login:login }

_security_logout:
    pattern: /logout
    defaults: { _controller: TvDatabaseHomeBundle:Login:logout}

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
