jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
#        TvDatabase\LoginBundle\Entity\User: sha512
#        FOS\UserBundle\Model\UserInterface: sha512
        

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
#        administrators: 
#            entity: { class: TvDatabaseLoginBundle:User }
#        fos_userbundle:
#            id: fos_user.user_provider.username

#    firewalls:
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#            logout:       true
#            anonymous:    true
    firewalls:
#        tvdatabase_secured:
#            pattern:   /api/.*
#            security:      true
        public: 
            pattern:   ^/.*
            anonymous: true
            security: true
            fos_facebook:
                app_url: "http://apps.facebook.com/tvprogramschedule/"
                server_url: "http://www.symfony1server.com/"
                login_path: /login
                check_path: /login_check
                default_target_path: /
            logout: 
                path: /logout
                target: /
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login:
#            pattern:  ^/demo/secured/login$
#            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login: 
                 login_path: /login
                 check_path: /login_check
            #pattern:    ^/demo/secured/
            #form_login:
            #    check_path: /demo/secured/login_check
            #    login_path: /demo/secured/login
            #logout:
            #    path:   /demo/secured/logout
            #    target: /demo/
        admin_area: 
            pattern: ^/admin
            http_basic: ~
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/secured/.*, role: IS_AUTHENTICATED_FULLY } # This is the route secured with fos_facebook
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
