<?php

namespace Proxies\__CG__\Acme\StoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MetaEAVAttribute extends \Acme\StoreBundle\Entity\MetaEAVAttribute implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getAttributeId()
    {
        $this->__load();
        return parent::getAttributeId();
    }

    public function setDefaultValue($defaultValue)
    {
        $this->__load();
        return parent::setDefaultValue($defaultValue);
    }

    public function getDefaultValue()
    {
        $this->__load();
        return parent::getDefaultValue();
    }

    public function setDatatype($datatype)
    {
        $this->__load();
        return parent::setDatatype($datatype);
    }

    public function getDatatype()
    {
        $this->__load();
        return parent::getDatatype();
    }

    public function setAttributeName($attributeName)
    {
        $this->__load();
        return parent::setAttributeName($attributeName);
    }

    public function getAttributeName()
    {
        $this->__load();
        return parent::getAttributeName();
    }

    public function setRegularExpressionMatch($regularExpressionMatch)
    {
        $this->__load();
        return parent::setRegularExpressionMatch($regularExpressionMatch);
    }

    public function getRegularExpressionMatch()
    {
        $this->__load();
        return parent::getRegularExpressionMatch();
    }

    public function addEntitySet(\Acme\StoreBundle\Entity\MetaEAVAttributeSet $entitySets)
    {
        $this->__load();
        return parent::addEntitySet($entitySets);
    }

    public function removeEntitySet(\Acme\StoreBundle\Entity\MetaEAVAttributeSet $entitySets)
    {
        $this->__load();
        return parent::removeEntitySet($entitySets);
    }

    public function getEntitySets()
    {
        $this->__load();
        return parent::getEntitySets();
    }

    public function addValue(\Acme\StoreBundle\Entity\EAVAttributeValue $values)
    {
        $this->__load();
        return parent::addValue($values);
    }

    public function removeValue(\Acme\StoreBundle\Entity\EAVAttributeValue $values)
    {
        $this->__load();
        return parent::removeValue($values);
    }

    public function getValues()
    {
        $this->__load();
        return parent::getValues();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'AttributeId', 'DefaultValue', 'Datatype', 'AttributeName', 'RegularExpressionMatch', 'entitySets', 'values');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}